version: 0.3.2
commit: 'chore: bump to v%.%.%'
files:
  README.md:
    - deploy_dir v%.%.%
    - 'https://deno.land/x/deploy_dir@v%.%.%/cli.ts'
  cli.ts: const VERSION = "%.%.%";
  mod.ts: 'https://deno.land/x/deploy_dir@v%.%.%'
  mod_test.ts: 'https://deno.land/x/deploy_dir@v%.%.%'
