import {
  assertEquals,
  assertThrowsAsync,
} from "https://deno.land/std@0.97.0/testing/asserts.ts";
import { getMediaType, readDirCreateSource } from "./mod.ts";

Deno.test("readDirCreateSource", async () => {
  assertEquals(
    await readDirCreateSource("testdata"),
    `
// This script is generated by https://deno.land/x/deploy_dir@v0.1.6
console.log("init");
const dirData: Record<string, [Uint8Array, string]> = {};
dirData["/bar.ts"] = [Uint8Array.from(atob("Y29uc29sZS5sb2coImJhciIpOwo="), (c) => c.charCodeAt(0)), "text/typescript"];
dirData["/foo.txt"] = [Uint8Array.from(atob("Zm9vCg=="), (c) => c.charCodeAt(0)), "text/plain"];
dirData["/index.html"] = [Uint8Array.from(atob("SGVsbG8hCg=="), (c) => c.charCodeAt(0)), "text/html"];
addEventListener("fetch", (e) => {
  let { pathname } = new URL(e.request.url);
  if (pathname.endsWith("/")) {
    pathname += "index.html";
  }
  let data = dirData[pathname];
  if (!data) {
    data = dirData[pathname + '.html'];
  }
  if (data) {
    const [bytes, mediaType] = data;
    e.respondWith(new Response(bytes, { headers: { "content-type": mediaType } }));
    return;
  }
  e.respondWith(new Response("404 Not Found", { status: 404 }));
});
`.trim(),
  );
});

Deno.test("readDirCreateSource - toJavaScript", async () => {
  assertEquals(
    await readDirCreateSource("testdata", undefined, { toJavaScript: true }),
    `
// This script is generated by https://deno.land/x/deploy_dir@v0.1.6
console.log("init");
const dirData = {};
dirData["/bar.ts"] = [Uint8Array.from(atob("Y29uc29sZS5sb2coImJhciIpOwo="), (c) => c.charCodeAt(0)), "text/typescript"];
dirData["/foo.txt"] = [Uint8Array.from(atob("Zm9vCg=="), (c) => c.charCodeAt(0)), "text/plain"];
dirData["/index.html"] = [Uint8Array.from(atob("SGVsbG8hCg=="), (c) => c.charCodeAt(0)), "text/html"];
addEventListener("fetch", (e) => {
  let { pathname } = new URL(e.request.url);
  if (pathname.endsWith("/")) {
    pathname += "index.html";
  }
  let data = dirData[pathname];
  if (!data) {
    data = dirData[pathname + '.html'];
  }
  if (data) {
    const [bytes, mediaType] = data;
    e.respondWith(new Response(bytes, { headers: { "content-type": mediaType } }));
    return;
  }
  e.respondWith(new Response("404 Not Found", { status: 404 }));
});
`.trim(),
  );
});

Deno.test("readDirCreateSource - with basic auth", async () => {
  await assertThrowsAsync(
    async () => {
      await readDirCreateSource("testdata", undefined, {
        basicAuth: "user-pw",
      });
    },
    Error,
    "Invalid form of basic auth creadentials: user-pw",
  );
});

Deno.test("readDirCreateSource - with basic auth", async () => {
  assertEquals(
    await readDirCreateSource("testdata", undefined, { basicAuth: "user:pw" }),
    `
// This script is generated by https://deno.land/x/deploy_dir@v0.1.6
import { basicAuth } from "https://deno.land/x/basic_auth@v1.0.0/mod.ts";
console.log("init");
const dirData: Record<string, [Uint8Array, string]> = {};
dirData["/bar.ts"] = [Uint8Array.from(atob("Y29uc29sZS5sb2coImJhciIpOwo="), (c) => c.charCodeAt(0)), "text/typescript"];
dirData["/foo.txt"] = [Uint8Array.from(atob("Zm9vCg=="), (c) => c.charCodeAt(0)), "text/plain"];
dirData["/index.html"] = [Uint8Array.from(atob("SGVsbG8hCg=="), (c) => c.charCodeAt(0)), "text/html"];
addEventListener("fetch", (e) => {
  const unauthorized = basicAuth(e.request, "Access to the site", {"user":"pw"});
  if (unauthorized) {
    e.respondWith(unauthorized);
    return;
  }

  let { pathname } = new URL(e.request.url);
  if (pathname.endsWith("/")) {
    pathname += "index.html";
  }
  let data = dirData[pathname];
  if (!data) {
    data = dirData[pathname + '.html'];
  }
  if (data) {
    const [bytes, mediaType] = data;
    e.respondWith(new Response(bytes, { headers: { "content-type": mediaType } }));
    return;
  }
  e.respondWith(new Response("404 Not Found", { status: 404 }));
});`.trim(),
  );
});

Deno.test("readDirCreateSource with root", async () => {
  assertEquals(
    await readDirCreateSource("testdata", "/root"),
    `
// This script is generated by https://deno.land/x/deploy_dir@v0.1.6
console.log("init");
const dirData: Record<string, [Uint8Array, string]> = {};
dirData["/root/bar.ts"] = [Uint8Array.from(atob("Y29uc29sZS5sb2coImJhciIpOwo="), (c) => c.charCodeAt(0)), "text/typescript"];
dirData["/root/foo.txt"] = [Uint8Array.from(atob("Zm9vCg=="), (c) => c.charCodeAt(0)), "text/plain"];
dirData["/root/index.html"] = [Uint8Array.from(atob("SGVsbG8hCg=="), (c) => c.charCodeAt(0)), "text/html"];
addEventListener("fetch", (e) => {
  let { pathname } = new URL(e.request.url);
  if (pathname.endsWith("/")) {
    pathname += "index.html";
  }
  let data = dirData[pathname];
  if (!data) {
    data = dirData[pathname + '.html'];
  }
  if (data) {
    const [bytes, mediaType] = data;
    e.respondWith(new Response(bytes, { headers: { "content-type": mediaType } }));
    return;
  }
  e.respondWith(new Response("404 Not Found", { status: 404 }));
});
`.trim(),
  );
});

Deno.test("readDirCreateSource with root 2", async () => {
  assertEquals(
    await readDirCreateSource("testdata", "root"),
    `
// This script is generated by https://deno.land/x/deploy_dir@v0.1.6
console.log("init");
const dirData: Record<string, [Uint8Array, string]> = {};
dirData["/root/bar.ts"] = [Uint8Array.from(atob("Y29uc29sZS5sb2coImJhciIpOwo="), (c) => c.charCodeAt(0)), "text/typescript"];
dirData["/root/foo.txt"] = [Uint8Array.from(atob("Zm9vCg=="), (c) => c.charCodeAt(0)), "text/plain"];
dirData["/root/index.html"] = [Uint8Array.from(atob("SGVsbG8hCg=="), (c) => c.charCodeAt(0)), "text/html"];
addEventListener("fetch", (e) => {
  let { pathname } = new URL(e.request.url);
  if (pathname.endsWith("/")) {
    pathname += "index.html";
  }
  let data = dirData[pathname];
  if (!data) {
    data = dirData[pathname + '.html'];
  }
  if (data) {
    const [bytes, mediaType] = data;
    e.respondWith(new Response(bytes, { headers: { "content-type": mediaType } }));
    return;
  }
  e.respondWith(new Response("404 Not Found", { status: 404 }));
});
`.trim(),
  );
});

Deno.test("getMediaType", () => {
  assertEquals(getMediaType("README.md"), "text/markdown");
  assertEquals(getMediaType("index.html"), "text/html");
  assertEquals(getMediaType("inde.htm"), "text/html");
  assertEquals(getMediaType("package.json"), "application/json");
  assertEquals(getMediaType("image.jpg"), "image/jpeg");
  assertEquals(getMediaType("image.jpeg"), "image/jpeg");
  assertEquals(getMediaType("image.avif"), "image/avif");
  assertEquals(getMediaType("image.webp"), "image/webp");
  assertEquals(getMediaType("image.png"), "image/png");
  assertEquals(getMediaType("image.gif"), "image/gif");
  assertEquals(getMediaType("foo.txt"), "text/plain");
  assertEquals(getMediaType("foo.ts"), "text/typescript");
  assertEquals(getMediaType("Component.tsx"), "text/tsx");
  assertEquals(getMediaType("script.js"), "application/javascript");
  assertEquals(getMediaType("Component.jsx"), "text/jsx");
  assertEquals(getMediaType("archive.tar.gz"), "application/gzip");
  assertEquals(getMediaType("style.css"), "text/css");
  assertEquals(getMediaType("lib.wasm"), "application/wasm");
  assertEquals(getMediaType("mod.mjs"), "application/javascript");
  assertEquals(getMediaType("logo.svg"), "image/svg+xml");
});
